### ISSUE TITLE
Code review of function_app.py

### ISSUE THREAD

**Issue by paulyuk** [Azure-Samples/functions-quickstart-python-http-azd#1]
Some observations and suggestions:
[ ] Functions auth not set.  Suggest Functions level auth set at the `app` level in the constructure, so all functions operators inherit.  
[ ] Do we need to set app.Functionname if app.route is set?
[ ] http_post should explicitly set methods["post"], and http_get should do methods["get"] to control exposure and be clear
[ ] emit a log entry similar to other quickstarts
[ ] imports logging and time unused (logging will be used once above is fixed)
[ ] style and old convention to leave empty line at the end of the file for linux users

Suggest comparing with this one:
https://github.com/paulyuk/musicstore-orders-function/blob/main/function_app.py

**Comment by shreyabatra4** [comment]
Thanks - made these changes. Function name is not needed, I added for clarity. Though, since this is pretty bare bones it is not needed, and I have removed.
