### ISSUE TITLE
Files and folders to be ignored

### ISSUE THREAD

**Issue by paulyuk** [Azure-Samples/functions-quickstart-python-http-azd#2]
Please delete the following and add to .gitignore so they don't sneak back in.  

[ ] delete `local.settings.json`
[ ] delete `__pycache__` folder
[ ] delete `.env` folder
[ ] delete `image` folder
[ ] *include a `.gitignore` -- here is one: https://github.com/paulyuk/musicstore-orders-function/blob/main/.gitignore

**Comment by shreyabatra4** [comment]
Thanks! Included these changes.
